Repository NewCherish/Cherish-Server, pull requests merged in 2023-01, with the labels that each got.

#6 Setting: EB, docker, actions 인프라 세팅
  .github/workflows/develop.yml
  Dockerfile.dev
  docker-compose.yml
  package.json
  src/main.ts
  yarn.lock
Labels: 🧑🏼‍🚀 jobchae, ⚙️ setting

#7 Setting: swagger 세팅
  .gitignore
  .prettierrc
  package.json
  src/config/swagger.ts
  src/main.ts
  yarn.lock
Labels: 🧑🏼‍🚀 jobchae, ⚙️ setting

#8 Fix: 최종 IA에 맞게 DB 스키마 수정
  prisma/migrations/20230105060951_editwithia/migration.sql
  prisma/migrations/20230105075140_edit_with_ia/migration.sql
  prisma/schema.prisma
Labels: 🛠 fix, 🍯 Honey, 📀 DB

#10 Feat: sentry, 에러 핸들링
  package.json
  src/app.module.ts
  src/config/configuration.ts
  src/exceptions/custom.exception.ts
  src/exceptions/global.exception.ts
  src/interceptors/webhook.interceptor.ts
  src/main.ts
  src/utils/success.ts
  yarn.lock
Labels: 🧑🏼‍🚀 jobchae, 🙋🏻 feat, ⚙️ setting
